### PR TITLE
Files with bacnet units for submission

### PR DESCRIPTION
**Pull request by anetakoleva**
In the folder /submissions I have added the two files with new units for submission

### CODE REVIEW

**Comment by steveraysteveray** [comment]
Aneta,
You are trying to merge into the wrong branch. Here's what you need to do:
1. Do a git pull of qudt-public-repository:master
2. Do a git merge master into your branch to check for merge conflicts
3. Do a git push of your branch to your fork
4. Submit a pull request of your master branch into the qudt-public-repository:master branch

Let me know if you would like help with this.

**Comment by steveraysteveray** [comment]
Aneta, I closed this PR so you could open a new one.

**Comment by steveraysteveray** [comment]
Nevermind. I'll open this one again.

**Comment by anetakoleva** [comment]
I did the steps and I changed the branch here. 
Is the pull request okay now? I have also removed one of the files that I submitted earlier.

**Comment by steveraysteveray** [comment]
Yes, everything is ready now. Thanks for fixing all that.
I think Jack will be reviewing.

**Comment by anetakoleva** [comment]
Great! Thanks for the help.

**Comment by anetakoleva** [comment]
Hello Jack,
I did the corrections to the units that you mentioned.
I also added a conversion multiplier for MegaJ-PER-K.
Let me know if there is anything else I should do.

**Pull request merged**
