### PR TITLE
request to add new unit:MegaGM-PER-HA

### PR DESCRIPTION
**Pull request by elisagirola**

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Already there in practice - http://qudt.org/vocab/unit/TONNE-PER-HA

**Review by steveraysteveray — CHANGES_REQUESTED** [review]
The dimension vector should be qkdv:A0E0L-2I0M1H0T0D0  (i.e. per unit area, not per unit volume).
The quantity kind should be quantitykind:MassPerArea

Also, please add the following two lines:
  qudt:exactMatch unit:TON_Metric-PER-HA ;
  qudt:exactMatch unit:TONNE-PER-HA ;

The unece Code you list is for Mega gram per cubic metre, so that isn't right. I couldn't find a suitable unece Code, so you should just delete that line.

**Review by steveraysteveray — CHANGES_REQUESTED** [review]
Sorry to drag this out, but I forgot to check the iec61360 code, and it seems that one is for Mega gram per metre cubed, so I think we need to delete that line as well.

**Review by steveraysteveray — APPROVED** [review]

**Comment by jhodgesatmb** [comment]
Instead of deleting unece and iec61360 codes because they are wrong, we should strive to find out the appropriate codes. Deleting them takes this unit out of sight and thus out of mind.

**Comment by steveraysteveray** [comment]
I strived (strove?) and failed to find them.

**Comment by elisagirola** [comment]
Thanks All. Much appreciated

**Pull request merged**
