### PR TITLE
P06 additions from spreadsheet (converted to TTL using SKOS-Play!)

### PR DESCRIPTION
**Pull request by dr-shorthair**

### CODE REVIEW

**Comment by steveraysteveray** [comment]
Quick review of your units.ttl file. This is much easier - will definitely think about making the SKOS-Play! spreadsheet template into a submission template.

Rather than my cloning your fork and submitting a branch back to you, would you consider just making the following edits?

Add the following triple to all new units:
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;

Change all labels starting with "per ..." to "Reciprocal ..." (12 instances)

Replacing all strings of "by weight" in dct:description to "by mass" (4 instances)

Curious why you decided on the qname unit:PH_ACIDITY instead of just unit:PH? I recall from high school that there is also POH for the OH radical, but not sure if P<something> occurs elsewhere?
Also, on PH_ACIDITY, wouldn't the dimension be A1L-3? (Amount of substance per volume, right?) Admittedly not linear, but we can capture the dimension.

Typo:
unit:BQ-SEC-PER-M3 a qudt:Unit;
  dct:description "TBC"@en
to
unit:BQ-SEC-PER-M3 a qudt:Unit;
  dct:description "TBD"@en

In rdfs:label, change all "xyz squared" to "square xyz" (11 instances)

**Comment by steveraysteveray** [comment]
Thinking about PH, since it is the negative logarithm, maybe the dimension is the reciprocal...  A-1L3?

**Comment by dr-shorthair** [comment]
I've processed all the changes requested, and added a comment in the entry for PH.

**Comment by dr-shorthair** [comment]
@gwemon @nicholascar We are most of the way now. Just a whole lot of missing quantity-kind links from unit definitions.

**Review by steveraysteveray — APPROVED** [review]
We can discuss the dimensionality of PH going forward...

**Comment by dr-shorthair** [comment]
Fixes #268

**Pull request merged**
