### PR TITLE
qudt:Concept as per Issue 39

### PR DESCRIPTION
**Pull request by nicholascar**
As per https://github.com/qudt/qudt-public-repo/issues/39

### CODE REVIEW

**Comment by steveraysteveray** [comment]
We're still discussing.
Meanwhile, of course, you can just have an "overlay" file in your workspace with this declaration.

**Comment by steveraysteveray** [comment]
We discussed some more. The issue is the implication of applying skos behavior on concepts that aren't really terminological. The main exception is QuantityKind, which IS terminological, even though it also has object properties. 
In other words, what would it mean to say one Unit instance is skos:broader than another?
On the other hand, this makes sense for QuantityKind, where, say, Energy is broader than MechanicalEnergy.
How would you feel about only declaring qudt:QuantityKind as a subClass of skos:Concept, rather than all qudt:Concept classes being so declared?

**Comment by dr-shorthair** [comment]
You clearly have a view on the meaning of 'terminological' which is stronger than mine! 
AFAIK `skos:Concept` is effectively a weak form of `rdfs:Class`. 
What is `qudt:Concept`?

**Comment by steveraysteveray** [comment]
My understanding is that a skos:Concept is a "term" that can be applied to an actual "concept". 
qudt:Concept is itself a "concept" in the sense of conceptual modeling.
https://terms.tdwg.org/wiki/Term_versus_Concept

**Comment by dr-shorthair** [comment]
`skos:Concept` is precisely the same thing - it is an abstract notion, with one or more preferred and alternative labels per natural language. The URI identifies the concept, not the label. i.e. the concept comes first, not the term.  https://www.w3.org/TR/skos-primer/#secconcept

**Comment by steveraysteveray** [comment]
Yes, I see what you are referring to.  However, I'm still asking the question about Unit versus QuantityKind above (https://github.com/qudt/qudt-public-repo/pull/57#issuecomment-607972036). I don't know how one Unit can be broader or narrower than another, while I CAN understand that for QuantityKinds.

**Comment by dr-shorthair** [comment]
It is not mandatory to incorporate `skos:broader` and 'skos:narrower` assertions in your vocabulary. These are convenience properties, to be used when the subject matter matches, but not otherwise.

**Comment by dr-shorthair** [comment]
I would see `qudt:generalization rdfs:subPropertyOf skos:broader.` but that does not imply that skos:broader shoudl be used on non-QuantityKind indidivduals.

**Comment by steveraysteveray** [comment]
In the end, we discussed this again and have concluded that we will not include the "qudt:Concept rdfs:subClassOf skos:Concept" assertion in the QUDT schema, primarily because we cannot anticipate its impact on our other users. It's a global change.

**Comment by dr-shorthair** [comment]
Ok - we are looking at the same issue (SKOS is a widely adopted schema) and coming to opposite conclusions 
- I see the benefits in aligning and leveraging SKOS services and infrastructure, 
- you see alignment as introducing risks

I understand that premature alignment can be seen as an anti-pattern, and that adopting SKOS could be seen as introducing some poorly defined semantics into a more strongly axiomatized framework. But could I suggest adding an alignment graph, as a separate file in the QUDT distribution, so people who would like to leverage the alignment have some guidance here? It would really only need two axioms:
```
qudt:Concept rdfs:subClassOf skos:Concept .
qudt:generalization rdfs:subPropertyOf skos:broader. 
```

**Comment by steveraysteveray** [comment]
Interesting suggestion. I'll bring it up at the next Board meeting. Perhaps we could include a discussion of this in the documentation, such as on the wiki pages.

**Comment by steveraysteveray** [comment]
Nicholas & Simon,
I think we have a solution that will satisfy all of us. Please see https://github.com/qudt/qudt-public-repo/wiki/Advanced-User-Guide#customizing-the-qudt-ontology and PR #104.

**Comment by dr-shorthair** [comment]
None of the links work on the Wiki page :-(

**Comment by nicholascar** [comment]
I think Simon’s referring to the fact that when we visit the web addresses on that wiki page, http://qudt.org/2.1/schema/extensions/imports & http://qudt.org/2.1/schema/extensions/skos, we see a 404: Page not found.

The "Advanced User Guide" webpage itself works!

By the way, I’m about to start serious work on the geoprofile of QUDT since the Department I work for has collated all the Units they use in the geoscience area.

**Comment by steveraysteveray** [comment]
Ah, thanks for the clarification. It's true that those URIs don't resolve, but they aren't intended to. They are just the base URIs of the two graphs in question.

Great news on the geo-profile. Issue #43 is still open.

**Pull request closed without merging**
