### PR TITLE
UCUM codes for the derived units

### PR DESCRIPTION
**Pull request by dr-shorthair**
Tedious work, trying to do a bit at a time. 
Draft PR for the moment as I've only got up to the megas and millis so far.

### CODE REVIEW

**Review by steveraysteveray — COMMENTED** [review]
First, thanks so much for doing this thankless work!
(Although, I suppose by thanking you it is no longer thankless :)

I notice you have some values typed ^^qudt:UCUMcs, and others are not typed. Shouldn't they all have that type? If so, an easy SPARQL fix.

**Comment by dr-shorthair** [comment]
Yes, they should all be `^^qudt:UCUMcs`. It gets set automatically by TBCME when entering values using the `Instances` tab, but not if you use the TBCME Form. I was planning to fix them all at the end with a SPARQL query. 

FWIW this validation tool is quite nice, and provides a consistent textual label for any valid UCUM code - https://ucum.nlm.nih.gov/ucum-lhc/demo.html

**Review by steveraysteveray — APPROVED** [review]

**Comment by dr-shorthair** [comment]
Just discovered this is incomplete, because I had max # instances=1000 in TopBraid, while there are >2000 units. 
More drudgery.

**Comment by steveraysteveray** [comment]
Your efforts are greatly appreciated!!!

**Comment by dr-shorthair** [comment]
Well I have a great drive towards harmonization, and if we could get QUDT+UCUM playing nice together, then I think we win. 

UCUM has a huge penetration in biomedical. I understand it is built in to FHIR which is the main game now. It is also very rational and generally highly consistent. A few gaps, but not many. Best would be to do all this algorithmically of course, but that's beyond my skillset.

**Pull request merged**
