### PR TITLE
No longer restrict maven CI to PRs that have been closed

### LINKED ISSUE #1050: Maven CI is not triggered for PRs from forks

### PR DESCRIPTION
**Pull request by fkleedorfer**
Fixes #1050

### CODE REVIEW

**Review by steveraysteveray — COMMENTED** [review]
Does this change mean that the validation is done only when the PR is created (which would not have any changes yet, right?)

Why not have it run with each push? Too much?

If the GitHub defaults were different, I would recommend it runs each time a PR is switched from "draft" to "ready for review", but since the default is "ready for review", people rarely use the "draft" state anyway, so this would not really help.

Or here's an idea: Have the validation run when manually invoked via the Actions tab on GitHub. This avoids too many runs, but allows submitters to validate without any local installation of Maven. We would then request submitters to run it when submitting a PR, and reviewers could also easily run it if it was missed.

**Comment by fkleedorfer** [comment]
As far as I can tell, this runs the CI action every time someone pushes to a PR that is targeted at the main branch

**Comment by fkleedorfer** [comment]
For example, in this PR, the action was executed because of the `pull_request` event, not the `push` event as it would have before.
grafik

**Comment by steveraysteveray** [comment]
So are you saying it runs upon a push and also runs on a pull request?

**Review by steveraysteveray — APPROVED** [review]

**Comment by steveraysteveray** [comment]
The action doesn't look like it ran. Also, the latest snapshot release was last week.

**Comment by fkleedorfer** [comment]
True, it does not run on main when the PR gets merged. But I believe it will run on PRs from forks upon each push, possibly after we allow it.

**Comment by fkleedorfer** [comment]
I'll give it another try, adding the push event with the main branch filter...

**Pull request merged**
