### PR TITLE
Draft: Introduce a build process based on maven

### PR DESCRIPTION
**Pull request by fkleedorfer**
This is a - for now prototypical - implementation of a build process based on maven. If we move forward with it, we will eventually have to port it to a new branch so as to retain the change histories of our rdf files.

## Structure
- pom.xml: defines the build process
- src/main/rdf - rdf sources
- src/main/resources - other  stuff
- target - the folder generated during the build process

## Operations
- check format of all ttl files under src/main/rdf
   - (fix formatting by calling spotless plugin explicitly)
- calculate applicableUnits 
- check the SHACL rules on the union of all vocab files, the inferred data and the schema. 

Addresses #959

### CODE REVIEW

**Comment by jhodgesatmb** [comment]
Should the build process maybe be in R2?Jack Hodges, Ph.D.Arbor StudiosOn Sep 24, 2024, at 6:28 AM, Florian Kleedorfer ***@***.***> wrote:﻿
@fkleedorfer requested your review on: #975 Draft: Introduce a build process based on maven as a code owner.

**Comment by fkleedorfer** [comment]
what's R2?

**Comment by jhodgesatmb** [comment]
It is the QUDT development branch. It is where we keep ‘code’ related things, for example.Jack Hodges, Ph.D.Arbor StudiosOn Sep 24, 2024, at 7:05 AM, Florian Kleedorfer ***@***.***> wrote:﻿
what's R2?

**Comment by fkleedorfer** [comment]
> Should the build process maybe be in R2?

I don't think so. Having the build in the public repo allows every contributor to build the whole thing and execute all the checks if they want. Moreover if the build is in this repo, we can trigger it upon PR in a github action and the checks are executed automatically. Less work for everyone. Plus, contributors can improve the build process, too

**Comment by jhodgesatmb** [comment]
I have had projects in R2 that were later moved to public.Jack Hodges, Ph.D.Arbor StudiosOn Sep 24, 2024, at 9:55 AM, Florian Kleedorfer ***@***.***> wrote:﻿

Should the build process maybe be in R2?

I don't think so. Having the build in the public repo allows every contributor to build the whole thing and execute all the checks if they want. Moreover if the build is in this repo, we can trigger it upon PR in a github action and the checks are executed automatically. Less work for everyone. Plus, contributors can improve the build process, too

**Comment by jhodgesatmb** [comment]
You wanted to check it in so I offered an option to get it into the got tracking. It can be moved into the public repo later when it goes operational. We have done this before. I am not dictating anything; just offering an idea.Jack Hodges, Ph.D.Arbor StudiosOn Sep 24, 2024, at 11:58 AM, Jack Hodges ***@***.***> wrote:﻿I have had projects in R2 that were later moved to public.Jack Hodges, Ph.D.Arbor StudiosOn Sep 24, 2024, at 9:55 AM, Florian Kleedorfer ***@***.***> wrote:﻿

Should the build process maybe be in R2?

I don't think so. Having the build in the public repo allows every contributor to build the whole thing and execute all the checks if they want. Moreover if the build is in this repo, we can trigger it upon PR in a github action and the checks are executed automatically. Less work for everyone. Plus, contributors can improve the build process, too

**Comment by jhodgesatmb** [comment]
Sorry, responded to the earlier message as that was what was shown when I opened the mail. That said, I still believe what I said is the best approach.Jack Hodges, Ph.D.Arbor StudiosOn Oct 27, 2024, at 8:38 PM, Jack Hodges ***@***.***> wrote:﻿You wanted to check it in so I offered an option to get it into the got tracking. It can be moved into the public repo later when it goes operational. We have done this before. I am not dictating anything; just offering an idea.Jack Hodges, Ph.D.Arbor StudiosOn Sep 24, 2024, at 11:58 AM, Jack Hodges ***@***.***> wrote:﻿I have had projects in R2 that were later moved to public.Jack Hodges, Ph.D.Arbor StudiosOn Sep 24, 2024, at 9:55 AM, Florian Kleedorfer ***@***.***> wrote:﻿

Should the build process maybe be in R2?

I don't think so. Having the build in the public repo allows every contributor to build the whole thing and execute all the checks if they want. Moreover if the build is in this repo, we can trigger it upon PR in a github action and the checks are executed automatically. Less work for everyone. Plus, contributors can improve the build process, too

**Comment by fkleedorfer** [comment]
Closing in favor of the same PR off a branch in the qudt-public-repo repository instead of a fork

**Pull request closed without merging**
