### PR TITLE
fix wrong values for qudt:uneceCommonCode

### PR DESCRIPTION
**Pull request by Toni100**
discovered by Wikidata cross-checks

I verified the corrections by looking at the latest revision 16 of recommendation 20 on the official website:
https://unece.org/trade/uncefact/cl-recommendations

### CODE REVIEW

**Comment by jhodgesatmb** [comment]
It is easier to check if you say which units your source says are incorrect and why. Otherwise we have to check everything.

**Comment by Toni100** [comment]
The link I provided is the authoritative source who produces those identifiers.
The units which have been changed can be seen in the diff. Would that be enough?
I used Wikidata to see which values might be wrong (Wikidata is not a primary source), and then fixed the ones which were actually wrong by looking into the official document.

**Comment by jhodgesatmb** [comment]
I ask partly because the UNECE codes were provided to us or acquired by us directly from the source, so have they changed their codes? Secondly, my request was not about the source of information but of the comment in the PR. If the PR comment tells me to look at a specific list of units then the review is easier.

**Comment by steveraysteveray** [comment]
Thanks, Toni! I reviewed all 5 of your suggested changes, and you are absolutely correct. The only exception is that I couldn't find A99 (bit) in the spreadsheet. Was that in some secret place?

**Comment by Toni100** [comment]
@jhodgesatmb: Take for instance `D27`, which was present on both `unit:M2-PER-SR` and `unit:SR` - two dimensionally incompatible units. This looks pretty clearly like a typo. (That might have been wrong in the source, too, but confirming that would require some archeology on the older source revisions - maybe not worth our time.)

@steveraysteveray: `A99` appears in the third table (Annex II & Annex III). For some weird reason there is a filter activate on this table. Disabling it (menu Data -> AutoFilter in LibreOffice) makes all entries appear.

**Comment by Toni100** [comment]
PS: Looking for codes which appear on different units which are not `owl:sameAs` might be a way to discover more such typos.

**Comment by steveraysteveray** [comment]
Got it! Thanks.

**Review by steveraysteveray — APPROVED** [review]

**Pull request merged**
