### PR TITLE
 Fixed description of M3

### PR DESCRIPTION
**Pull request by steveraysteveray**

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Fixes #108

**Comment by steveraysteveray** [comment]
Nice, Simon. A more elegant way of closing the issue!

**Comment by dr-shorthair** [comment]
Hmm - still showing 1m^3 is 106cm^3 - http://qudt.org/vocab/unit/M3 
Something in the rendering pipeline?

**Comment by steveraysteveray** [comment]
Ah yes. This PR was merged on 4/24/2020, but the html and ttl pages on the web were last regenerated on 4/18/2020. It takes several hours to regenerate, which I only do every few weeks.  Maybe I should bite the bullet and do another round.

**Pull request merged**
