### PR TITLE
 Removed unit:CFU

### PR DESCRIPTION
**Pull request by steveraysteveray**

### CODE REVIEW

**Review by fkleedorfer — APPROVED** [review]
As a sidenote, in some cases (maybe this one, not sure) it might be helpful to add a deprecation explanation a) for our future selves because even the best forget and b) for users stumbling upon the deprecated flag

**Comment by steveraysteveray** [comment]
I'm thinking that when we migrate to QUDT 3.0 we would use that occasion to delete all the deprecated entities. We would have to all agree on that of course.

But your larger point, definitely worth considering. I'm going to go ahead and merge for now.

**Comment by steveraysteveray** [comment]
@fkleedorfer, this PR indicates the check passed, but under the Actions tab it looks like it fails because it was unable to delete the snapshot release. Also, I notice there is no longer a snapshot listed as a Release any more. Is this what you expect?

**Comment by fkleedorfer** [comment]
Well this deleting the release step has never run before. Now that it actually runs, we see it is somehow wrong. Next pr to the rescue. Sorry for the inconvenience

**Comment by steveraysteveray** [comment]
No apologies! The test loop is a slow one here...

**Pull request merged**
