### PR TITLE
Small refactoring of scaling, addition of factor units and conversion targets

### PR DESCRIPTION
**Pull request by fkleedorfer**
(Note: This PR includes the changes of #457 )

The reasoning for the suggested changes is developed in #455.

# Changes
The following changes were made (in this order):
1. Fix the 'OZ_PER' typos. 
2. Add a comment in the schema, clarifying what qudt:isScalingOf means, and delete some triples not compatible with this meaning.
3. 
    * Add the notion of `factor units` to the schema: a small addition by which one connects derived units, such as `unit:PER-M3` to its base unit, e.g. `unit:M` and the exponent that is applied, e.g. `-3`. 
    * Based on the unit names, generate `qudt:isScalingOf`, `qudt:convertsTo`, and `qudt:factorUnit/qudt:unit`, `qudt:factorUnit/qudt:exponent` triples.
    * factor units implied by unit IRIs but not actually present in the units file are generated in the process.

# Queries that generate the added triples

The triples in 3. are generated with these queries:

```
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX prefix: <http://qudt.org/vocab/prefix/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
 ?scaledUnit
    qudt:isScalingOf ?baseUnit ;
    qudt:prefix ?prefix ;
    qudt:convertsTo ?convertsTo .
}
#SELECT ?scaledUnit ?baseUnit ?convertsTo ?prefix
where
{
    {
        {

            {
                # select all base units (not using prefixes)
                ?scaledUnit a qudt:Unit ;
                    BIND(REPLACE(STR(?scaledUnit), "^.+/", "") as ?scaledUnitLocalName)
                    FILTER EXISTS {
                        ?prefix
                            a qudt:Prefix ;
                            rdfs:label ?prefixLabel
                        FILTER(CONTAINS(?scaledUnitLocalName, STR(?prefixLabel)))
                    }
            }

            {
                SELECT (CONCAT("\\b(",GROUP_CONCAT(STR(?prefixLabel); separator ="|"), ")") as ?prefixRegex) where
                {
                    ?prefix
                        a qudt:Prefix ;
                        rdfs:label ?prefixLabel .
                 }
            }

        }

        # select all base units (not using prefixes)
        # special handling for prefix + time, e.g.
        # 'unit:MegaYR qudt:isScalingOf unit:YR', not unit:SEC

        ?baseUnit a qudt:Unit ;
        BIND(REPLACE(STR(?baseUnit), "^.+/", "") as ?baseUnitLocalName)
        BIND("(YR|MO|DAY|HR|MIN)\\b" as ?timeRegex)
        FILTER (
                    (
                        REPLACE(?scaledUnitLocalName, CONCAT(?prefixRegex, ?timeRegex), "") = ?scaledUnitLocalName
                        && ?baseUnitLocalName = REPLACE(REPLACE(?scaledUnitLocalName, ?prefixRegex, ""), ?timeRegex, "SEC")
                    ) || (
                        REPLACE(?scaledUnitLocalName, CONCAT(?prefixRegex, ?timeRegex), "") != ?scaledUnitLocalName
                        && ?baseUnitLocalName = REPLACE(?scaledUnitLocalName, ?prefixRegex, "")
                    )
        )
    }
    OPTIONAL {
        ?prefix a qudt:Prefix ;
            rdfs:label ?prefixLabel ;
            FILTER (!CONTAINS(?baseUnitLocalName, "-"))
            FILTER (CONTAINS(?scaledUnitLocalName, STR(?prefixLabel)))
    }
    OPTIONAL {
        ?scaledUnit qudt:conversionMultiplier ?scaledMultiplier . # require any multiplier
        ?baseUnit
            qudt:conversionMultiplier ?cm .
        optional {
            ?baseUnit qudt:conversionOffset ?co
        }
        FILTER( !BOUND(?co) || ?co = 0 )
        FILTER( ?cm = 1 )
        BIND(?baseUnit as ?convertsTo)
    }
}
order by ?baseUnit ?scaledUnit
```
and
```
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX prefix: <http://qudt.org/vocab/prefix/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
    ?derivedUnit qudt:factorUnit [
        qudt:unit ?baseUnit ;
        qudt:exponent ?exponent
    ] .
    ?baseUnit a ?missingUnitType ;
        rdfs:comment ?comment .
}
#SELECT * WHERE
#select count(*) where
{
    {
        SELECT distinct ?derivedUnit ?exponent ?baseUnitLocalNameExtracted ?baseUnit
        WHERE
        {
            ?derivedUnit a qudt:Unit ;
                BIND(REPLACE(STR(?derivedUnit), "^.+/", "") as ?derivedUnitLocalName)
            FILTER(REPLACE(?derivedUnitLocalName, "(PER|2|3|4|5|6|-)\\b", "") != ?derivedUnitLocalName)
            FILTER(?derivedUnitLocalName NOT IN (
                "Gold-OunceTroy",
                "Palladium-OunceTroy",
                "Silver-OunceTroy",
                "Platinum-OunceTroy",
                "failures-in-time",
                "USDollar-NextDay"
            ))

            VALUES ?skipUnits { 0 1 2 3 4 5 6 }
            BIND("(\\w+(_\\w+)?\\d?)" as ?baseUnitRegex)
            BIND("(\\w+(_\\w+)?\\d?|PER)" as ?skipUnitRegex)
            BIND(CONCAT("^(",?skipUnitRegex,"-){", STR(?skipUnits), "}", ?baseUnitRegex, "(-" ,?skipUnitRegex, ")*$") as ?selectUnitRegex )
            BIND(REPLACE(?derivedUnitLocalName, ?selectUnitRegex, "$4") as ?baseUnitLocalNameExtractedTmp)
            BIND(REPLACE(?baseUnitLocalNameExtractedTmp, "^(\\w*[^\\d])(\\d?)$", "$1") as ?baseUnitLocalNameExtracted)
            BIND(REPLACE(?baseUnitLocalNameExtractedTmp, "^(\\w*[^\\d])(\\d?)$", "$2") as ?exponentTmpStr)
            BIND(IF(?exponentTmpStr = "", STRDT("1",xsd:integer), STRDT(?exponentTmpStr,xsd:integer)) as ?exponentTmp)
            VALUES ( ?matchString ?dontMatchString ?expFactor) {
                ( "^.*PER-.*\\b@@UNIT@@\\b.*$" "dontfindthis" -1 )
                ( "^.*\\b@@UNIT@@\\b.*PER.*$" "dontfindthis"  1 )
                ( ".+" "\\bPER\\b" 1 )
            }
            FILTER(REPLACE(?derivedUnitLocalName, REPLACE(?matchString, "@@UNIT@@", ?baseUnitLocalNameExtractedTmp), "") != ?derivedUnitLocalName)
            FILTER(REPLACE(?derivedUnitLocalName, ?dontMatchString, "") = ?derivedUnitLocalName)
            BIND(?exponentTmp * ?expFactor as ?exponent)
            FILTER( ?baseUnitLocalNameExtractedTmp != "PER" )
            FILTER( ! CONTAINS(?baseUnitLocalNameExtractedTmp, "-") )
            BIND(IRI(CONCAT("http://qudt.org/vocab/unit/", ?baseUnitLocalNameExtracted)) as ?baseUnit)
        }
    }

    OPTIONAL {
        ?baseUnit a qudt:Unit .
        BIND(true as ?baseUnitExists)
    }
    OPTIONAL {
        BIND ("This unit was added while generating qudt:factorUnit information as a missing factor unit"@en as ?comment)
        BIND (qudt:Unit as ?missingUnitType)
        FILTER(!BOUND(?baseUnitExists))
    }
}
order by ?derivedUnit ?baseUnit
```

# Use cases

With this PR, one can find units based on prefix and unit name using the follwing query:
```
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# bind ?baseUnitLabel and ?prefixLabel, get the scaled unit
SELECT * where
{
    #VALUES (?prefixLabel ?baseUnitLabel ) { ("Pico" "Meter") }

    ?unit a qudt:Unit;
       rdfs:label ?label ;
       qudt:isScalingOf ?baseUnit ;
       qudt:prefix ?prefix ;
       qudt:isScalingOf ?baseUnit .

    ?baseUnit a qudt:Unit ;
        rdfs:label ?actualBaseUnitLabel .

    ?prefix a qudt:Prefix ;
        rdfs:label ?actualPrefixLabel .

    FILTER(UCASE(STR(?actualBaseUnitLabel)) = UCASE(?baseUnitLabel))
    FILTER(UCASE(STR(?actualPrefixLabel)) = UCASE(?prefixLabel))
    optional {
       ?unit qudt:conversionMultiplier ?conversionMultiplier
    }
    optional {
        ?unit qudt:hasQuantityKind ?quantityKind
    }
    optional {
           ?unit qudt:conversionOffset ?conversionOffset
        }
    optional {
       ?unit qudt:symbol ?symbol
    }
}
```

To get the unit if you know the factor units and exponents (in this case, 3 factor units):
```
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Bind
# ?baseUnit1 ?exponent1 ?baseUnit2 ?exponent2 ?baseUnit3 ?exponent3
# to get the derived unit as ?unit
SELECT * WHERE
{
    {
        #VALUES (?baseUnit1 ?exponent1 ?baseUnit2 ?exponent2 ?baseUnit3 ?exponent3) { (unit:MOL 1 unit:M -2 unit:SEC -1 ) }
        ?unit a qudt:Unit ;
           rdfs:label ?label ;
           qudt:factorUnit ?factorUnit1 ;
           qudt:factorUnit ?factorUnit2 ;
           qudt:factorUnit ?factorUnit3 .
        ?factorUnit1
            qudt:unit ?baseUnit1 ;
            qudt:exponent ?exponent1 .
        ?factorUnit2
            qudt:unit ?baseUnit2 ;
            qudt:exponent ?exponent2 .
        ?factorUnit3
            qudt:unit ?baseUnit3 ;
            qudt:exponent ?exponent3 .
        ?baseUnit1 a qudt:Unit .
        ?baseUnit2 a qudt:Unit .
        ?baseUnit3 a qudt:Unit .

        # force binding different factors
        FILTER(?factorUnit1 NOT IN (?factorUnit2, ?factorUnit3))
        FILTER(?factorUnit2 NOT IN (?factorUnit1, ?factorUnit3))

        #make sure we have no other factor units
        OPTIONAL {
            ?unit qudt:factorUnit ?factorUnitX .
            FILTER(?factorUnitX NOT IN(?factorUnit1, ?factorUnit2, ?factorUnit3))
        }
        FILTER( !BOUND(?factorUnitX) )
    }

    OPTIONAL {
        ?unit qudt:prefix ?prefix
    }
    OPTIONAL {
       ?unit qudt:conversionMultiplier ?conversionMultiplier
    }
    OPTIONAL {
        ?unit qudt:hasQuantityKind ?quantityKind
    }
    OPTIONAL {
        ?unit qudt:conversionOffset ?conversionOffset
    }
    OPTIONAL {
        ?unit qudt:symbol ?symbol
    }
}
```

# Future work

One open issue will be to find all scaled units that don't have `qudt:convertsTo` triples because their base unit itself converts to another unit. In these cases, the base unit has to be annotated manually and the triples then generated for all of its scaled units.

Another issue could be to look for missing based units for scaled units. I did not check, but it's quite possbile that for some units with scaling prefix there is no base unit.

EDIT: fixed the factorUnit query (see also commit 799e47f)

### CODE REVIEW

**Comment by fkleedorfer** [comment]
One more bit of future work would be to annotate those derived units whose name does not hint at the fact that they are derived, such as Newton as kg.m/s^2.

**Comment by fkleedorfer** [comment]
> One more bit of future work would be to annotate those derived units whose name does not hint at the fact that they are derived, such as Newton as kg.m/s^2.

I just added that with commit 09da19a, for all SI derived units with special names, as per https://en.wikipedia.org/wiki/SI_derived_unit

**Comment by fkleedorfer** [comment]
Just added commit 799e47f, which adds a bunch of qudt:factorUnit triples that had been missing, such as those of `unit:N-M`

**Comment by steveraysteveray** [comment]
Florian,
First, thanks for the effort you have clearly put in to improve QUDT. As an open-source activity, this is the lifeblood of scalable progress.

You have raised numerous issues in this pull request. Your previous PR and the one I created to address your other issues dealt with making changes to the units vocabulary. This PR, on the other hand, is making a number of suggestions for changes/additions to the QUDT schema itself. Such changes raise many issues relating to vocabulary maintenance, generality and perhaps most importantly, to the parsimony of the models and vocabularies. What I mean by that is the question of derivability of information from a compact representation, versus the convenience of explicit information in a more verbose data set at the risk of inconsistency and file size. 

One of the principles we try to adhere to is "DRY", i.e. "Don't repeat yourself". If a given piece of information can be derived by what is already there, perhaps it is better to not include it separately. Other factors to consider include the support for non-SI systems of measure. For example, the cgs system sometimes has non-integer dimension vector values. Further, how would we model the non-SI relations for factorUnit, scalingOf, etc?

You raise some important suggestions. As it happens, we plan to launch a quarterly design discussion meeting the last Monday of each quarter, for sustaining corporate sponsors where these kinds of schema changes are considered. We are currently planning the first one for Monday, March 28th at 8am USA Pacific time (for USA and Europe) and at 2pm USA Pacific time (for Asia). If your company would consider becoming a sustaining corporate sponsor, your needs could be on the agenda. The corporate support level is shown [here](https://github.com/sponsors/qudt).

In the meantime, updates to the vocabularies and other suggestions that are simpler to implement are greatly appreciated. They could be handled in separate pull requests.

Please contact me if you would like help in discussing corporate (or individual) sponsorship options.

Best,
- Steve

**Comment by fkleedorfer** [comment]
Hi @steveraysteveray, thanks for the update. 

I am sorry to have to admit that 2000$ per month for corporate support level is way out of the ballpark for the non-profit research organization that I work for, but thanks for the invitation. I'll look into the other options though.

As to the DRY principle: 
> "DRY", i.e. "Don't repeat yourself". If a given piece of information can be derived by what is already there, perhaps it is better to not include it separately. 

I could not agree more on DRY, but I do not agree that it applies to this PR. I spent a good amount of time making those triples explicit, mostly working upon the local names of the units (the naming conventions are great!), and doing a lot of unconventional string/regex munging. The queries aren't fast, so it's not something you'd like to do in production. One may consider an automated post-processing step in the publishing process but then you lose the option to fix problems manually. Maybe publishing the triples in a separate vocab would make sense? 
But: yes, I agree, if this is adopted in QUDT, keeping unit names consistent with factorUnit and scalingOf becomes a maintenance issue  - but at least we've got some queries that we can use to check for problems ;-) 

> Other factors to consider include the support for non-SI systems of measure. For example, the cgs system sometimes has non-integer dimension vector values. 

That's interesting - but I think it's no problem. Just extend the range of the `qudt:exponent` and add the triples... or I am missing the point, which would not surprise me.

> Further, how would we model the non-SI relations for factorUnit, scalingOf, etc?

Not being an expert on units, I'd need to look at some examples to even understand the question, I guess. As it stands, `qudt:scalingOf` somehow relates to a unit being defined in multiples of another unit using prefixes or maybe other modifiers on the name. There probably are exceptions, like kg and ton (which, btw, I have missed in the PR so far). `qudt:factorUnit` might be specific to SI and its way of combining units/dimensions.... I don't know.

Anyway, I think I for my use case, I can generate the triples locally as needed, and time permitting, I'll publish a Java library on github using the information offered in the PR - which may help you to understand the usefulness of the addition. 

I will keep updating the branch of the PR to reflect my development and rebase it regularly. I don't plan on new features, just fixing bugs/omissions (like the ton/kg thing mentionend earlier).

**Comment by fkleedorfer** [comment]
FYI, I just published version 1.0 of qudtlib to maven central, which is based on the adaptations discussed here. 

https://github.com/qudtlib/qudtlib-java

I will keep this up to date with the releases of QUDT, and I am planning to add a typescript version of the library.

Feedback is always welcome - and I guess we can close this PR, Cheers!

**Comment by steveraysteveray** [comment]
This is great! Thanks for embarking on your project. I'll close this PR, and follow your repo with interest.

**Pull request closed without merging**
