### PR TITLE
A number of cleanups of quantity kinds and referring entities

### PR DESCRIPTION
**Pull request by steveraysteveray**

### CODE REVIEW

**Comment by dr-shorthair** [comment]
`breadth` ?
Depth is a very tricky one, mind you. Furniture dimensions and water column would look at it very differently.

**Comment by steveraysteveray** [comment]
Agreed. The best I can think of is that the description is only suggestive of some uses, but not definitive. If someone really has heartache, they can suggest further specializations that have a skos:broader of depth.

**Comment by jhodgesatmb** [comment]
Sadly, what people refer to as length, width, depth, height, breadth, etc are often, as Simon mentions, context dependent. But they are all measurements of size along a Cartesian dimension.

Jack Hodges, Ph.D.
Arbor Studios

**Comment by jhodgesatmb** [comment]
Is Length a QuantityKind then, and the variations use skos:narrower?

Jack Hodges, Ph.D.
Arbor Studios

**Comment by steveraysteveray** [comment]
Pretty much. The variations would use skos:broader to point to Length, or some other variant. 
See the skos taxonomy for Energy. 

 
- Steve

**Comment by jhodgesatmb** [comment]
Ok

Jack Hodges, Ph.D.
Arbor Studios

**Pull request merged**
