### PR TITLE
Add mega tonne per yr

### PR DESCRIPTION
**Pull request by JurekMueller**
* Adds unit MegaTONNE-PER-YR
* Corrects ucumCode for TeraW-HR-PER-YR

### CODE REVIEW

**Comment by fkleedorfer** [comment]
Thanks for your submission! Please follow these easy steps to format the sources to allow the build to succeed: https://github.com/qudt/qudt-public-repo/wiki/Formatting-the-source-via-GitHub-Workflow

**Comment by fkleedorfer** [comment]
Apart from the formatting, this looks good to me.

**Review by fkleedorfer — CHANGES_REQUESTED** [review]
As soon as formatting is applied, this PR should be ok.

**Comment by JurekMueller** [comment]
Thank you for your review. I have applied the formatting action now.

**Review by fkleedorfer — APPROVED** [review]

**Comment by fkleedorfer** [comment]
Darn, forgot about the Changelog. Would you mind making another PR adding the changes to the changelog under Added and Fixed headings, linking to your github profile as it was done in the changes leading up to the latest release?

**Pull request merged**
