### PR TITLE
Added a new unit: K.d

### PR DESCRIPTION
**Pull request by fennibay**
Hi, I'd like to introduce this new unit, we need it for our application.

It's my first contribution to this repo. I read the readme and contribution guidelines, and checked similar MRs. So I hope I'm doing everything right. :-)

Many thanks.

### CODE REVIEW

**Review by steveraysteveray — APPROVED** [review]
Looks good to me.

**Comment by fennibay** [comment]
Vow, so fast. Thanks :-D

**Comment by dr-shorthair** [comment]
(In the code, but not yet the website build. )

**Comment by steveraysteveray** [comment]
Indeed. You will be happy to hear, Simon, that we are getting closer to republishing via https links! I'll be working on that next week.

**Pull request merged**
