### PR TITLE
Convert doubles and floats to decimals

### LINKED ISSUE #307: Use of xsd:decimal instead of xsd:double for conversion factors
Using a [comparison of unit ontologies with ABECTO](https://github.com/fusion-jena/abecto-unit-ontology-comparison) I became aware that QUDT uses `xsd:double` to represent conversion factors and offsets. I think, instead `xsd:decimal` should be used, as binary floating point datatypes are not able to exactly represent many of the conversion values. Especially 0.1, 0.01, 0.001, … can not be represented. Only the lexical representation seems to be exact. However, the lexical to value mapping will map them to a slightly different value. This runs the risk of numerical problems in applications. I outlined this in detail in [arXiv:2011.08077](https://arxiv.org/abs/2011.08077).

### PR DESCRIPTION
**Pull request by dr-shorthair**
Fixes #307

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Used the following SPARQL

INSERT { ?u qudt:conversionMultiplier ?md }
WHERE {
	?u a qudt:Unit ;
		qudt:conversionMultiplier ?m .
	BIND( DATATYPE(?m) as ?mt )
	FILTER( ?mt != xsd:decimal )
	BIND( xsd:decimal(?m) as ?md )
}

DELETE { ?u qudt:conversionMultiplier ?m }
WHERE {
	?u a qudt:Unit ;
		qudt:conversionMultiplier ?m .
	BIND( DATATYPE(?m) as ?mt )
	FILTER( ?mt != xsd:decimal )
}

INSERT { ?u qudt:conversionOffset ?od }
WHERE {
	?u a qudt:Unit ;
		qudt:conversionOffset ?o .
	BIND( DATATYPE(?o) as ?ot )
	FILTER( ?ot != xsd:decimal )
	BIND( xsd:decimal(?o) as ?od )
}

DELETE { ?u qudt:conversionOffset ?o }
WHERE {
	?u a qudt:Unit ;
		qudt:conversionOffset ?o .
	BIND( DATATYPE(?o) as ?ot )
	FILTER( ?ot != xsd:decimal )
}

Also - remove all zero offets

DELETE { ?u qudt:conversionOffset ?o }
WHERE {
	?u a qudt:Unit ;
		qudt:conversionOffset ?o .
	FILTER( ?o = 0.0 )
}

**Comment by nicholascar** [comment]
> remove all zero offets

Is this because it is inferred to be zero if not present by calculation queries?

**Comment by dr-shorthair** [comment]
Offsets apply in very few cases - and only on interval scales (not ratio scales). 
As they are the exceptional case, they need not be present in general. 
(AFAICT there are only 3 valid offsets in the current catalogue.)

**Review by steveraysteveray — APPROVED** [review]
OK.
I hope the multiplier for PlanckDensity doesn't break anything!

**Pull request merged**
