### PR TITLE
Fix snapshot release deletion

### PR DESCRIPTION
**Pull request by fkleedorfer**

### CODE REVIEW

**Comment by fkleedorfer** [comment]
Running the manual CI action on this branch with 'force snapshot release' on to see whether the changes work

**Comment by fkleedorfer** [comment]
seems to work: 
grafik

**Comment by fkleedorfer** [comment]
Something goes wrong when the changelog is appended to the release body:

grafik

**Review by steveraysteveray — APPROVED** [review]

**Comment by fkleedorfer** [comment]
Finally.

**Pull request merged**
