### PR TITLE
 Tweaked unit:UNITLESS to refer to quantitykind:Count

### PR DESCRIPTION
**Pull request by steveraysteveray**

### CODE REVIEW

**Comment by dr-shorthair** [comment]
> [Tweaked unit:UNITLESS to refer to quantitykind:Count](https://github.com/qudt/qudt-public-repo/pull/632/commits/0098b8b13d1f1b2d072d8bb72dd966429bc3d57e)

I was a little worried at this description, but then checked that `quantitykind:Count` was _in addition to_ a whole bunch of other quantity kinds.

**Review by jhodgesatmb — COMMENTED** [review]
Are all unit:UNITLESS quantities of quantitykind:Count?

**Comment by steveraysteveray** [comment]
@jhodgesatmb, I'm not sure I understand your question. As you know, we don't manage a vocabulary of quantities. Are you asking about units that are somehow related to unit:UNITLESS, or about other quantitykinds that are related to quantitykind:Count?

**Comment by steveraysteveray** [comment]
Still needs to be merged.

**Review by jhodgesatmb — APPROVED** [review]

**Pull request merged**
