### PR TITLE
Fix the namespace IRI of qudt.type:

### PR DESCRIPTION
**Pull request by ektrah**
Based on the discussion in https://github.com/qudt/qudt-public-repo/pull/681

@steveraysteveray, please take a look. I'm not sure if I did this right.

It might be easier to review the commits individually than the whole PR.

I didn't try to fix [VOCAB_QUDT-DATATYPES--sDEPRECATED-v2.1.ttl](https://github.com/qudt/qudt-public-repo/blob/main/vocab/types/TBR/VOCAB_QUDT-DATATYPES--sDEPRECATED-v2.1.ttl) since it's marked as deprecated.

### CODE REVIEW

**Comment by ektrah** [comment]
Related to https://github.com/qudt/qudt-public-repo/issues/289

**Comment by steveraysteveray** [comment]
The "T" in QUDT is intended to support a robust type model (not unlike what a strongly typed compiler might have), distinct from the values of Units or QuantityKinds. We haven't revisited our earlier work on this, but we want to keep the existing type schema as is for now, distinct from the concepts in the QUDT schema itself. We want to support concepts such as arrays, vectors, tensors, time series, and even arrays of types, but there are many distinctions involved. Therefore, we would rather hold off on any edits to the type schema/prefixes until that time.

**Comment by jhodgesatmb** [comment]
What is the motivation for this request? The datatypes graph is an invaluable component of QUDT for engineering. Do you want a cleaner prefix/namespace or do you want other changes, and why?

**Comment by ektrah** [comment]
As mentioned in https://github.com/qudt/qudt-public-repo/pull/681#issuecomment-1513163362, I was looking at the IRIs in the files of the QUDT v2.1.26 release that show up as predicates and/or objects but never as subjects. This is often an indication that something in the ontology is different than intended (e.g. because a typo has crept in). If after review it is clear that the IRI is correct and it never appears as a subject on purpose, nothing needs to be done.

When it comes to data types, I noticed that QUDT v2.1.26 uses e.g. both `<http://qudt.org/schema/qudt/Double_X>` and `<http://qudt.org/schema/type#Double_X>` , which (at least at first glance) seems like an obvious inconsistency. So I created this PR (just like all the other PRs) in the hope that this inconsistency could be solved quickly. If it doesn't, feel free to close 🙂

**Pull request closed without merging**
